export const LANGUAGES = {
  ID: {
    hint: {
      appName: "Catatanku",
      toLoginPage: "sudah memiliki akun? ",
      toRegisterPage: "belum memiliki akun? ",
      emptyNoteList: "belum ada catatan",
      invalidNote: "catatan tidak ditemukan",
      passwordInvalid: "password tidak sama",
      loading: "memuat...",
      addNotePage: "Buat catatan Baru",
    },
    links: {
      home: "Beranda",
      add: "Tambah",
      login: "Masuk",
      register: "Buat baru",
    },
    notelist: {
      archived: "Telah Diarsipkan",
      unArchived: "Catatan Aktif",
    },
    button: {
      archived: "arsipkan",
      delete: "hapus",
      unArchived: "nonarsipkan",
      addnotes: "tambahkan catatan",
      login: "masuk",
      register: "daftar",
      logout: "keluar",
    },
    form: {
      email: "Email",
      password: "Sandi",
      confirmPassword: "Konfirmasi Sandi",
      username: "Nama",
      title: "Judul",
      desc: "Deskripsi",
    },
  },
  ENG: {
    hint: {
      appName: "Notes App",
      toLoginPage: "already have account? ",
      toRegisterPage: "dont have account? ",
      emptyNoteList: "no data to show",
      invalidNote: "current notes is unavailable",
      passwordInvalid: "incorrect password match",
      loading: "loading...",
      addNotePage: "Add notes",
    },
    links: {
      home: "Home",
      add: "Add",
      login: "Login",
      register: "Register",
    },
    notelist: {
      archived: "Archived Notes",
      unArchived: "Unarchived Notes",
    },
    button: {
      archived: "archive",
      delete: "delete",
      unArchived: "unarchive",
      addnotes: "Add Notes",
      login: "Login",
      register: "Register",
      logout: "Logout",
    },
    form: {
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm",
      username: "Username",
      title: "Title",
      desc: "Ddescription",
    },
  },
};
